### ISSUE TITLE
undefined method `logger' for Async:Module

### ISSUE THREAD

**Issue by lubosch** [serpapi/turbo_tests#17]
When running `bundle exec turbo_tests`.
Ruby 3.1, Async 2.0
Async.logger throws error also in irb console

**Comment by ilyazub** [comment]
@lubosch Thanks, I'll test this gem under Ruby 3. And fix will try to fix it.

**Comment by ilyazub** [comment]
`turbo_tests` work on Ruby 2.7, 3.0, 3.1, 3.2.

Here are GitHub Actions runs: https://github.com/serpapi/turbo_tests/actions/runs/5252614857/job/14212914295

@lubosch Feel free to share a repository with reproducible example if this issue still actual.
